name: null
favicon: null
layout_spectrum: 0.9807945056818426
typography_spectrum: 0.4557232775259763
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6098952235188335
  lightness: 0.6588348317891359
  saturation: 0.6807773900218308
  rhythmicContrast: 0.06135299406014383
purpose: []
